[simulation]
run_mechanical_interactions = true
bound_space = true

[visualization]
live = false
export = true
export_interval = 2

    [[visualize_sim_object]]
        name = "Cell"
        # additional_data_members = [ "cell_colour_" ]
